### PR TITLE
MHP-2417 reactive header

### PR DESCRIPTION
**Pull request by mikeallisonJS**
update headers to be reactive on smaller screens

fixes headers, but still has other component issues

### CODE REVIEW

**Comment by jesusfreak3** [comment]
@OzzieOrca  @mikeallisonJS  found some issues when quickly going through.

image

**Comment by jesusfreak3** [comment]
@mikeallisonJS @OzzieOrca also now on larger screens the sub menu is full screen, just put it in the "main-container" class it will resolve it.
image

**Comment by mikeallisonJS** [comment]
@jesusfreak3 @OzzieOrca I have addressed all but the search box. I couldn't find the width for the expanded view (always read 12px in chrome)

**Comment by OzzieOrca** [comment]
https://github.com/CruGlobal/missionhub-web/blob/sunset-legacy/src/components/navigation/navSearch.scss#L27

**Pull request merged**
